import { useState } from "react";
import { JurisdictionSelector, QuestionInput, AnswerCard, CitationCard, ErrorMessage, useRegimes } from "../components/ui";
import { compareQuery } from "../services/api";

export default function ComparePage() {
  const { label } = useRegimes();
  const [rs, setRs] = useState([]), [q, setQ] = useState(""), [k, setK] = useState(5);
  const [busy, setBusy] = useState(false), [err, setErr] = useState(""), [res, setRes] = useState(null);
  const go = async e => {
    e.preventDefault(); if (rs.length < 2) return setErr("Select at least two jurisdictions to compare.");
    setBusy(true); setErr(""); setRes(null);
    try { setRes(await compareQuery(q.trim(), rs, k)); } catch (x) { setErr(x.message); } finally { setBusy(false); }
  };
  return (
    <div className="main wide">
      <h1>Compare jurisdictions</h1><p className="muted">Ask one question and see each regime's answer and sources side by side.</p>
      <form onSubmit={go} className="glass pad">
        <label>Jurisdictions</label><JurisdictionSelector multi value={rs} onChange={setRs} />
        <QuestionInput value={q} onChange={setQ} k={k} onK={setK} busy={busy} label="Compare" pending="Retrieving sources for each jurisdiction..." />
      </form>
      <ErrorMessage m={err} />
      {res && <>
        {res?.ip_type &&
          res.ip_type !== "GENERAL" && (
            <span
              className="tag"
              style={{
                display: "inline-block",
                marginBottom: "12px",
              }}
            >
              Legal domain: {res.ip_type}
            </span>
          )}
        <div className="cmp">{res.per_regime_answers?.map(p => (
          <div key={p.regime} className="cc">
            <AnswerCard label={label(p.regime)} answer={p.answer} count={p.citations?.length || 0} />
            <details className="glass pad"><summary>Sources ({p.citations?.length || 0})</summary>{p.citations?.map((c, i) => <CitationCard key={i} c={c} n={i + 1} />)}</details>
          </div>))}</div>
        <article className="glass syn"><span className="tag">Comparison of the answers above</span><h3>Cross-Jurisdiction Synthesis</h3>
          <p className="muted">Generated by comparing the jurisdiction-specific answers, not from new sources.</p><p>{res.synthesis || "No synthesis was returned."}</p></article>
      </>}
    </div>
  );
}
